import { SareeProduct, CurrencyRate } from "./types";

export const CURRENCY_RATES: Record<string, CurrencyRate> = {
  USD: { code: "USD", symbol: "$", rate: 1 },
  INR: { code: "INR", symbol: "₹", rate: 86.5 },
  GBP: { code: "GBP", symbol: "£", rate: 0.79 },
  EUR: { code: "EUR", symbol: "€", rate: 0.92 },
  AED: { code: "AED", symbol: "AED ", rate: 3.67 },
};

export const SWATCH_BOX_OFFER = {
  id: "swatch-box-archive",
  title: "The Silk & Zari Tactile Swatch Archive",
  priceUSD: 25,
  description:
    "Four 4×4 inch touch-and-feel swatches of our handspun mulberry silk, wild tussar, Banarasi organza, and antique silver-plated matte zari yarn skeins. Shipped in unbleached mul-mul cotton. 100% credited toward your first heirloom acquisition.",
  image: "https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?q=80&w=800&auto=format&fit=crop",
};

export const SAREE_COLLECTION: SareeProduct[] = [
  {
    id: "saree-01",
    slug: "alabaster-monolith",
    title: "Swarna Hansa: The Alabaster Saree",
    culturalName: "स्वर्ण हंस (Golden Swan)",
    subTitle: "Pure Mulberry Kanchipuram Korvai Silk with Certified Matte Silver Zari",
    editionNumber: "01 / 18",
    totalPieces: 18,
    priceUSD: 1450,
    badge: "Master Weaver Heirloom",
    colorways: [
      {
        id: "cw-alabaster",
        name: "Raw Cocoon Alabaster",
        hex: "#F9F8F6",
        weftHex: "#EFECE6",
        zariHex: "#C5A059",
      },
      {
        id: "cw-iron",
        name: "Deep Cast Iron & Antique Gold",
        hex: "#1A1A18",
        weftHex: "#2D2C28",
        zariHex: "#B38E46",
      },
      {
        id: "cw-sage",
        name: "Vilvam Botanical Sage",
        hex: "#8A9A86",
        weftHex: "#A2B09F",
        zariHex: "#C5A059",
      },
    ],
    specs: {
      gsm: 210,
      weightGrams: 685,
      warpCount: "2/120s Degummed Pure Mulberry Silk",
      weftCount: "3-Ply Filature Cultivated Silk",
      composition: "98% Pure Mulberry Silk, 2% Certified Silver Electroplated Wire",
      loomType: "Traditional Two-Artisan Throw-Shuttle Pit Loom (Korvai Interlock)",
      originRegion: "Chinna Kanchipuram, Tamil Nadu",
      zariPurity: "Certified 1.8g Silver Electroplated Electro-lacquered Wire",
      weaveTimeDays: 24,
      transparency: "Opaque Architectural",
      dimensions: {
        sareeLengthMeters: 5.5,
        sareeWidthInches: 48,
        blouseLengthMeters: 1.0,
      },
    },
    provenance: {
      masterArtisan: "Ramanathan M.",
      lineage: "4th Generation Korvai Master Weaver",
      villageCluster: "Pillayar Palayam, Kanchipuram",
      loomHeritage: "Woven on a 60-year-old family pit loom with double wooden foot treadles",
      completionDate: "August 2026",
      portraitUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=400&auto=format&fit=crop",
      quote: "When two weavers toss shuttles across the Korvai divide in unison, the cloth breathes. You cannot rush silk tension.",
    },
    certification: {
      silkMarkLicenseNo: "SM-TN-2026-8841",
      silkMarkCertified: true,
      zariSilverPercentage: 98.2,
      zariLabReportUrl: "/docs/certificates/zari-test-saree-01.pdf",
      handloomMarkCertified: true,
      craftClusterRegNo: "IND-GI-TN-0012",
    },
    description:
      "Woven in the historic weavers' quarter of Chinna Kanchipuram, this heirloom celebrates the sacred Korvai interlocking technique where the border and body are woven with distinct shuttles without seams. Heavy pure mulberry silk yields structured, knife-sharp pleats that drape with regal grace.",
    philosophy:
      "A quiet tribute to the rhythm of two artisans working in synchrony. The oxidized antique zari reflects soft candlelight rather than synthetic flash.",
    auspiciousOccasions: [
      "Muhurtham Wedding Rituals",
      "Reception Soirée",
      "Cultural Diplomatic Galas",
      "Milestone Anniversaries",
    ],
    images: {
      hero: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1600&auto=format&fit=crop",
      drape: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1600&auto=format&fit=crop",
      macro: "https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?q=80&w=1600&auto=format&fit=crop",
      detail: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1600&auto=format&fit=crop",
      palluSpread: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1600&auto=format&fit=crop",
      modelDrape: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1600&auto=format&fit=crop",
      unboxing: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1200&auto=format&fit=crop",
    },
    videoUrls: {
      drapeWalkthrough: "https://assets.mixkit.co/videos/preview/mixkit-folds-of-a-luxurious-white-fabric-41712-large.mp4",
      loomProcess: "https://assets.mixkit.co/videos/preview/mixkit-hands-of-an-artisan-working-on-a-loom-42867-large.mp4",
    },
    blouseOption: {
      id: "blouse-01",
      title: "Handspun Raw Matka Silk Blouse Piece (1.0m)",
      priceUSD: 180,
      fabric: "100% Hand-reeled Matka Raw Silk in Cast Iron Carbon",
      image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=600&auto=format&fit=crop",
    },
    reviews: [
      {
        id: "rev-01",
        author: "Meenakshi Sundaram",
        verified: true,
        location: "London, UK",
        rating: 5,
        date: "2 weeks ago",
        occasion: "Daughter's Muhurtham Wedding",
        height: "5'6\" with 3\" heels",
        reviewText:
          "The weight of this silk is extraordinary. Unlike modern powerloom silks that slip and slide, these pleats stayed impeccably anchored for 8 hours of ceremony. The matte zari looked regal in the morning temple sunlight.",
        photoUrl: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=400&auto=format&fit=crop",
      },
      {
        id: "rev-02",
        author: "Ananya Deshmukh",
        verified: true,
        location: "Mumbai, India",
        rating: 5,
        date: "Last month",
        occasion: "Art Biennale Opening Gala",
        height: "5'8\"",
        reviewText:
          "The unboxing experience alone brought tears to my eyes. The acid-free cedar box and fresh mul-mul wrap kept the silk pristine. Master Ramanathan's signature on the loom certificate made it feel like a museum piece.",
      },
    ],
  },
  {
    id: "saree-02",
    slug: "gossamer-sage-mirage",
    title: "Marakatha Katan: The Sage Mirage",
    culturalName: "मरकत कातान (Emerald Mist)",
    subTitle: "Featherweight Banarasi Silk Organza with Watermark Tissue Weave",
    editionNumber: "02 / 12",
    totalPieces: 12,
    priceUSD: 1150,
    badge: "Limited Drop",
    colorways: [
      {
        id: "cw-sage",
        name: "Dried Botanical Sage",
        hex: "#8A9A86",
        weftHex: "#C5A059",
        zariHex: "#D8C8B8",
      },
      {
        id: "cw-alabaster",
        name: "Muted Sand Organza",
        hex: "#D8C8B8",
        weftHex: "#EAE3DB",
        zariHex: "#C5A059",
      },
    ],
    specs: {
      gsm: 64,
      weightGrams: 310,
      warpCount: "20/22 Denier High-Twist Katan Organza Silk",
      weftCount: "Handspun Organza Warp + Antique Tissue Zari",
      composition: "100% Pure Katan Silk Organza with Antique Gold Tissue Pallu",
      loomType: "Traditional Banarasi Frame Loom with Jacquard Punch-Cards",
      originRegion: "Madanpura, Varanasi, Uttar Pradesh",
      zariPurity: "Micro-Fine Electro-Oxidized Pale Antique Gold",
      weaveTimeDays: 16,
      transparency: "Gossamer",
      dimensions: {
        sareeLengthMeters: 5.5,
        sareeWidthInches: 46,
        blouseLengthMeters: 1.0,
      },
    },
    provenance: {
      masterArtisan: "Ustad Farooq Ansari",
      lineage: "6th Generation Banarasi Kadwa Weaver",
      villageCluster: "Madanpura, Varanasi",
      loomHeritage: "Woven on wooden frame looms facing the sacred ghats of the Ganges",
      completionDate: "July 2026",
      portraitUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop",
      quote: "Organza must not feel like plastic. When spun from real mulberry cocoon filaments, it floats on warm air like mist.",
    },
    certification: {
      silkMarkLicenseNo: "SM-UP-2026-3192",
      silkMarkCertified: true,
      zariSilverPercentage: 92.5,
      zariLabReportUrl: "/docs/certificates/zari-test-saree-02.pdf",
      handloomMarkCertified: true,
      craftClusterRegNo: "IND-GI-UP-0044",
    },
    description:
      "Weighing a mere 310 grams, The Sage Mirage redefines gossamer evening luxury. The silk organza is woven using ultra-fine high-twist filament threads that refract candlelight with a quiet, mist-like luminosity, holding its crisp form without puffing uncomfortably.",
    philosophy:
      "Weightlessness as a luxury proposition. A fluid cloud that moves with the wearer's micro-gestures.",
    auspiciousOccasions: [
      "Evening Cocktail Reception",
      "Sangeet & Dance Night",
      "Intimate Engagement Dinner",
      "Summer Wedding Soirée",
    ],
    images: {
      hero: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1600&auto=format&fit=crop",
      drape: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1600&auto=format&fit=crop",
      macro: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?q=80&w=1600&auto=format&fit=crop",
      detail: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1600&auto=format&fit=crop",
      palluSpread: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1600&auto=format&fit=crop",
      modelDrape: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1600&auto=format&fit=crop",
      unboxing: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1200&auto=format&fit=crop",
    },
    videoUrls: {
      drapeWalkthrough: "https://assets.mixkit.co/videos/preview/mixkit-folds-of-a-luxurious-white-fabric-41712-large.mp4",
      loomProcess: "https://assets.mixkit.co/videos/preview/mixkit-hands-of-an-artisan-working-on-a-loom-42867-large.mp4",
    },
    blouseOption: {
      id: "blouse-02",
      title: "Semi-Sheer Organza Blouse Piece with Crepe Lining (1.0m)",
      priceUSD: 160,
      fabric: "Pure Organza silk paired with 40g mulberry crepe lining",
      image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=600&auto=format&fit=crop",
    },
    reviews: [
      {
        id: "rev-03",
        author: "Pooja Varma",
        verified: true,
        location: "New York, NY",
        rating: 5,
        date: "3 weeks ago",
        occasion: "Brother's Sangeet in Napa Valley",
        height: "5'4\"",
        reviewText:
          "I danced for 5 hours without feeling weighed down. The organza has none of the scratchiness of commercial synthetic organzas—it felt like a second skin. Countless guests asked where I found this shade of sage.",
      },
    ],
  },
  {
    id: "saree-03",
    slug: "obsidian-veil-shot-silk",
    title: "Krishna Dhoop-Chhaon: The Obsidian Veil",
    culturalName: "धूप-छाँव (Sunlight & Shadow)",
    subTitle: "Dual-Tone Shot Silk Twill (Carbon Warp × Pale Botanical Olive Weft)",
    editionNumber: "03 / 15",
    totalPieces: 15,
    priceUSD: 1320,
    badge: "Curator's Choice",
    colorways: [
      {
        id: "cw-carbon-olive",
        name: "Cast Iron × Pale Olive",
        hex: "#1A1A18",
        weftHex: "#5E695A",
        zariHex: "#C5A059",
      },
      {
        id: "cw-tea-rose",
        name: "Ash Grey × Dried Mallow",
        hex: "#3D3C38",
        weftHex: "#8B7F74",
        zariHex: "#C5A059",
      },
    ],
    specs: {
      gsm: 175,
      weightGrams: 540,
      warpCount: "2/100s Mulberry Silk (Carbon Vat-Dyed)",
      weftCount: "2/80s Cross-Dyed Botanical Olive Filament",
      composition: "100% Hand-Reeled Pure Mulberry Silk",
      loomType: "Traditional Throw-Shuttle Pit Loom with Hand Selvedge",
      originRegion: "Arani Handloom Cluster, Tamil Nadu",
      zariPurity: "Zero Synthetic Zari — Pure Handloom Selvedge Ribbing with Raw Silk Cord",
      weaveTimeDays: 19,
      transparency: "Opaque Architectural",
      dimensions: {
        sareeLengthMeters: 5.5,
        sareeWidthInches: 47,
        blouseLengthMeters: 1.0,
      },
    },
    provenance: {
      masterArtisan: "Dhanalakshmi S.",
      lineage: "Master Weaver & Women's Handloom Collective Leader",
      villageCluster: "Arani Silk Cluster, Tamil Nadu",
      loomHeritage: "Cross-warp pit loom passed down through three generations of matriarch weavers",
      completionDate: "August 2026",
      portraitUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=400&auto=format&fit=crop",
      quote: "Dhoop-Chhaon is not two colors printed together. It is two lives woven together—one warp, one weft, shifting as you walk.",
    },
    certification: {
      silkMarkLicenseNo: "SM-TN-2026-6204",
      silkMarkCertified: true,
      zariSilverPercentage: 0,
      zariLabReportUrl: "/docs/certificates/silk-purity-saree-03.pdf",
      handloomMarkCertified: true,
      craftClusterRegNo: "IND-GI-TN-0038",
    },
    description:
      "An authentic exploration of Dhoop-Chhaon (Sunlight-Shadow). The warp is dyed in deep cast-iron charcoal while the weft carries botanical olive. As the wearer moves, the surface shifts subtly between midnight carbon depth and veiled green sheen.",
    philosophy:
      "Color as living optical movement rather than static dye. Understated luxury with zero metallic glitz.",
    auspiciousOccasions: [
      "Diplomatic Dinners & Galas",
      "Autumn Festive Soirées",
      "Private Salon Gatherings",
      "Gallery Openings",
    ],
    images: {
      hero: "https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1600&auto=format&fit=crop",
      drape: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1600&auto=format&fit=crop",
      macro: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1600&auto=format&fit=crop",
      detail: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1600&auto=format&fit=crop",
      palluSpread: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?q=80&w=1600&auto=format&fit=crop",
      modelDrape: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1600&auto=format&fit=crop",
      unboxing: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1200&auto=format&fit=crop",
    },
    videoUrls: {
      drapeWalkthrough: "https://assets.mixkit.co/videos/preview/mixkit-folds-of-a-luxurious-white-fabric-41712-large.mp4",
      loomProcess: "https://assets.mixkit.co/videos/preview/mixkit-hands-of-an-artisan-working-on-a-loom-42867-large.mp4",
    },
    blouseOption: {
      id: "blouse-03",
      title: "Coordinated Dual-Tone Silk Satin Blouse Piece (1.0m)",
      priceUSD: 195,
      fabric: "Pure 100g Mulberry Silk Satin in Charcoal",
      image: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?q=80&w=600&auto=format&fit=crop",
    },
    reviews: [
      {
        id: "rev-04",
        author: "Radhika Kirloskar",
        verified: true,
        location: "Singapore",
        rating: 5,
        date: "1 month ago",
        occasion: "Diwali Banquet at the High Commission",
        height: "5'7\"",
        reviewText:
          "The shot-silk duality is hypnotic. Indoors it looks like deep graphite, but under warm chandelier light the olive undertones come alive. This is high fashion rooted in Tamil handloom dignity.",
      },
    ],
  },
  {
    id: "saree-04",
    slug: "sand-architecture-tussar",
    title: "Vanya Maya: The Sand Architecture",
    culturalName: "वन्य माया (Forest Whispers)",
    subTitle: "Textured Wild Tussar Handloom with Matte Brushed Bronze Selvedge",
    editionNumber: "04 / 20",
    totalPieces: 20,
    priceUSD: 1280,
    badge: "Pure Organic Silk",
    colorways: [
      {
        id: "cw-sand",
        name: "Wild Cocoon Sand",
        hex: "#D8C8B8",
        weftHex: "#C5A059",
        zariHex: "#A88448",
      },
      {
        id: "cw-chalk",
        name: "Raw Calcite White",
        hex: "#F9F8F6",
        weftHex: "#E5DEC9",
        zariHex: "#C5A059",
      },
    ],
    specs: {
      gsm: 190,
      weightGrams: 590,
      warpCount: "Handspun Wild Tussar Filament",
      weftCount: "Raw Ghicha Slub Yarn (Unbleached)",
      composition: "100% Organic Wild Tussar Forest Silk",
      loomType: "Counterbalance Handloom with Bamboo Reed Shuttle",
      originRegion: "Bhagalpur Silk Guild, Bihar",
      zariPurity: "Matte Antique Brushed Bronze Selvedge Ribbon",
      weaveTimeDays: 21,
      transparency: "Semi-Sheer",
      dimensions: {
        sareeLengthMeters: 5.5,
        sareeWidthInches: 46,
        blouseLengthMeters: 1.0,
      },
    },
    provenance: {
      masterArtisan: "Birendra Das",
      lineage: "President, Bhagalpur Wild Silk Craftsmen Guild",
      villageCluster: "Champanagar, Bhagalpur, Bihar",
      loomHeritage: "Organic forest silk harvested without boiling cocoons (Ahimsa Silk tradition)",
      completionDate: "June 2026",
      portraitUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&auto=format&fit=crop",
      quote: "The slub in tussar silk is not an imperfection—it is the memory of the oak and asan trees the silkworm lived upon.",
    },
    certification: {
      silkMarkLicenseNo: "SM-BH-2026-1189",
      silkMarkCertified: true,
      zariSilverPercentage: 88.0,
      zariLabReportUrl: "/docs/certificates/tussar-purity-saree-04.pdf",
      handloomMarkCertified: true,
      craftClusterRegNo: "IND-GI-BH-0021",
    },
    description:
      "Preserving the organic slub texture of wild tussar cocoons. Unbleached and minimally processed, the tactile grain feels substantial and grounded, providing an earthen, breathable counterpoint to the slippery sheen of machine silks.",
    philosophy:
      "Celebrating the organic irregularities of forest ecology. Every slub carries the narrative of the forest canopy.",
    auspiciousOccasions: [
      "Daytime Weddings & Haldi Rituals",
      "Literature Festivals & Conclaves",
      "Executive Boardroom Banquets",
      "Poetic Garden Luncheons",
    ],
    images: {
      hero: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1600&auto=format&fit=crop",
      drape: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1600&auto=format&fit=crop",
      macro: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1600&auto=format&fit=crop",
      detail: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1600&auto=format&fit=crop",
      palluSpread: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1600&auto=format&fit=crop",
      modelDrape: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1600&auto=format&fit=crop",
      unboxing: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1200&auto=format&fit=crop",
    },
    videoUrls: {
      drapeWalkthrough: "https://assets.mixkit.co/videos/preview/mixkit-folds-of-a-luxurious-white-fabric-41712-large.mp4",
      loomProcess: "https://assets.mixkit.co/videos/preview/mixkit-hands-of-an-artisan-working-on-a-loom-42867-large.mp4",
    },
    blouseOption: {
      id: "blouse-04",
      title: "Handspun Slub Tussar Raw Silk Length (1.0m)",
      priceUSD: 175,
      fabric: "100% Hand-reeled Tussar Slub Silk in Wild Cocoon Sand",
      image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=600&auto=format&fit=crop",
    },
    reviews: [
      {
        id: "rev-05",
        author: "Devika Sen",
        verified: true,
        location: "Kolkata, India",
        rating: 5,
        date: "2 months ago",
        occasion: "Kolkata Literary Meet",
        height: "5'5\"",
        reviewText:
          "The raw texture of this wild tussar is unmatched. It breathes beautifully even in warm humid weather. The bronze border gives it an intellectual dignity without looking like flashy bridal wear.",
      },
    ],
  },
];

