import { SareeProduct, CurrencyRate } from "./types";

export const CURRENCY_RATES: Record<string, CurrencyRate> = {
  USD: { code: "USD", symbol: "$", rate: 1 },
  INR: { code: "INR", symbol: "₹", rate: 86.5 },
  GBP: { code: "GBP", symbol: "£", rate: 0.79 },
  EUR: { code: "EUR", symbol: "€", rate: 0.92 },
  AED: { code: "AED", symbol: "AED ", rate: 3.67 },
};

export const SAREE_COLLECTION: SareeProduct[] = [
  {
    id: "saree-01",
    slug: "alabaster-monolith",
    title: "The Alabaster Monolith",
    subTitle: "Pure Mulberry Kanchipuram Heavy Silk with Antique Matte Zari",
    editionNumber: "01 / 18",
    totalPieces: 18,
    priceUSD: 1450,
    badge: "Inaugural Edition",
    colorways: [
      {
        id: "cw-alabaster",
        name: "Raw Cocoon Alabaster",
        hex: "#F9F8F6",
        weftHex: "#EFECE6",
        zariHex: "#C5A059",
      },
      {
        id: "cw-iron",
        name: "Deep Cast Iron",
        hex: "#1A1A18",
        weftHex: "#2D2C28",
        zariHex: "#B38E46",
      },
      {
        id: "cw-sage",
        name: "Dried Botanical Sage",
        hex: "#8A9A86",
        weftHex: "#A2B09F",
        zariHex: "#C5A059",
      },
    ],
    specs: {
      gsm: 210,
      warpCount: "2/120s Degummed Mulberry Silk",
      weftCount: "3-ply Filature Silk",
      composition: "98% Pure Silk, 2% Antique Silver Zari Wire",
      loomType: "Traditional Pit Loom (Korvai Interlock)",
      originRegion: "Kanchipuram, Tamil Nadu",
      zariPurity: "Certified 1.8g Silver Electroplated Electro-lacquer",
      weaveTimeDays: 24,
      transparency: "Opaque Architectural",
    },
    description:
      "A study in sculptural purity. The Alabaster Monolith is woven using hand-reeled Mulberry silk on a traditional pit loom. The Korvai technique anchors an unbroken body to a subtle, zero-sheen border in oxidized pale zari, yielding a drape that holds crisp architectural lines without stiffness.",
    philosophy:
      "Stripping the ceremonial saree of ornamentation, we isolate the elemental dignity of silk tension and gravity.",
    images: {
      hero: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1600&auto=format&fit=crop",
      drape: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1600&auto=format&fit=crop",
      macro: "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?q=80&w=1600&auto=format&fit=crop",
      detail: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1600&auto=format&fit=crop",
    },
    blouseOption: {
      id: "blouse-01",
      title: "Unstitched Heavy Raw Matka Silk (1.2m)",
      priceUSD: 180,
      fabric: "100% Handspun Matka Raw Silk in Cast Iron Carbon",
      image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=600&auto=format&fit=crop",
    },
  },
  {
    id: "saree-02",
    slug: "gossamer-sage-mirage",
    title: "The Sage Mirage",
    subTitle: "Featherweight Banarasi Silk Organza with Watermark Tissue Weave",
    editionNumber: "02 / 12",
    totalPieces: 12,
    priceUSD: 1150,
    badge: "Limited Drop",
    colorways: [
      {
        id: "cw-sage",
        name: "Dried Botanical Sage",
        hex: "#8A9A86",
        weftHex: "#C5A059",
        zariHex: "#D8C8B8",
      },
      {
        id: "cw-alabaster",
        name: "Muted Sand Organza",
        hex: "#D8C8B8",
        weftHex: "#EAE3DB",
        zariHex: "#C5A059",
      },
    ],
    specs: {
      gsm: 64,
      warpCount: "20/22 Denier Highly Twisted Organza Silk",
      weftCount: "Handspun Organza Warp + Tissue Zari",
      composition: "100% Katan Silk Organza with Tissue Pallu",
      loomType: "Banarasi Frame Loom",
      originRegion: "Varanasi, Uttar Pradesh",
      zariPurity: "Micro-fine Electro-oxidized Pale Zari",
      weaveTimeDays: 16,
      transparency: "Gossamer",
    },
    description:
      "Weighing a mere 64 grams per square meter, The Sage Mirage redefines gossamer evening wear. The silk organza is woven with ultra-fine high-twist filament threads that refract candlelight with a quiet, mist-like luminosity.",
    philosophy:
      "Weightlessness as a luxury proposition. A fluid cloud that moves with the body's micro-gestures.",
    images: {
      hero: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1600&auto=format&fit=crop",
      drape: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1600&auto=format&fit=crop",
      macro: "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?q=80&w=1600&auto=format&fit=crop",
      detail: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1600&auto=format&fit=crop",
    },
    blouseOption: {
      id: "blouse-02",
      title: "Semi-Sheer Organza Blouse Length with Crepe Lining",
      priceUSD: 160,
      fabric: "Pure Organza silk paired with 40g mulberry crepe",
      image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=600&auto=format&fit=crop",
    },
  },
  {
    id: "saree-03",
    slug: "obsidian-veil-shot-silk",
    title: "The Obsidian Veil",
    subTitle: "Dual-Tone Shot Silk Twill (Carbon Warp × Pale Olive Weft)",
    editionNumber: "03 / 15",
    totalPieces: 15,
    priceUSD: 1320,
    badge: "Editorial Masterpiece",
    colorways: [
      {
        id: "cw-carbon-olive",
        name: "Cast Iron × Pale Olive",
        hex: "#1A1A18",
        weftHex: "#5E695A",
        zariHex: "#C5A059",
      },
      {
        id: "cw-tea-rose",
        name: "Ash Grey × Dried Mallow",
        hex: "#3D3C38",
        weftHex: "#8B7F74",
        zariHex: "#C5A059",
      },
    ],
    specs: {
      gsm: 175,
      warpCount: "2/100s Mulberry Silk",
      weftCount: "2/80s Cross-Dyed Filament",
      composition: "100% Hand-Reeled Pure Mulberry Silk",
      loomType: "Traditional Throw-Shuttle Pit Loom",
      originRegion: "Arani, Tamil Nadu",
      zariPurity: "Zero Zari — Pure Handloom Selvedge Ribbing",
      weaveTimeDays: 19,
      transparency: "Opaque Architectural",
    },
    description:
      "An exploration of Dhoop-Chhaon (Sunlight-Shadow). The warp is dyed in intense cast-iron charcoal while the weft carries botanical olive. As the wearer moves, the surface shifts subtly between near-black depth and veiled green sheen.",
    philosophy:
      "Optics over ornamentation. The colors exist not as applied dye, but as dynamic optical interference.",
    images: {
      hero: "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?q=80&w=1600&auto=format&fit=crop",
      drape: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1600&auto=format&fit=crop",
      macro: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1600&auto=format&fit=crop",
      detail: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1600&auto=format&fit=crop",
    },
    blouseOption: {
      id: "blouse-03",
      title: "Coordinated Dual-Tone Silk Satin Blouse Piece",
      priceUSD: 195,
      fabric: "Pure 100g Mulberry Silk Satin",
      image: "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?q=80&w=600&auto=format&fit=crop",
    },
  },
  {
    id: "saree-04",
    slug: "sand-architecture-tussar",
    title: "The Sand Architecture",
    subTitle: "Textured Wild Tussar Handloom with Matte Brushed Bronze Border",
    editionNumber: "04 / 20",
    totalPieces: 20,
    priceUSD: 1280,
    colorways: [
      {
        id: "cw-sand",
        name: "Wild Cocoon Sand",
        hex: "#D8C8B8",
        weftHex: "#C5A059",
        zariHex: "#A88448",
      },
      {
        id: "cw-chalk",
        name: "Raw Calcite White",
        hex: "#F9F8F6",
        weftHex: "#E5DEC9",
        zariHex: "#C5A059",
      },
    ],
    specs: {
      gsm: 190,
      warpCount: "Handspun Wild Tussar Silk",
      weftCount: "Raw Ghicha Slub Yarn",
      composition: "100% Organic Wild Tussar Silk",
      loomType: "Counterbalance Pedal Loom",
      originRegion: "Bhagalpur, Bihar",
      zariPurity: "Matte Antique Brushed Bronze Zari",
      weaveTimeDays: 21,
      transparency: "Semi-Sheer",
    },
    description:
      "Preserving the organic slub texture of wild tussar cocoons. Unbleached and minimally processed, the tactile grain feels substantial, providing a grounded, earthen counterpoint to the fluidity of mulberry silk.",
    philosophy:
      "Celebrating the irregularities of nature. Every slub tells the geography of the forest canopy.",
    images: {
      hero: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1600&auto=format&fit=crop",
      drape: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1600&auto=format&fit=crop",
      macro: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1600&auto=format&fit=crop",
      detail: "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?q=80&w=1600&auto=format&fit=crop",
    },
    blouseOption: {
      id: "blouse-04",
      title: "Unstitched Heavy Slub Raw Silk Length",
      priceUSD: 175,
      fabric: "100% Hand-reeled Tussar Slub",
      image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=600&auto=format&fit=crop",
    },
  },
];
